include: package:pedantic/analysis_options.1.9.0.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  enable-experiment:
    - non-nullable
  exclude:
    - 'example/**'

linter:
  rules:
    - public_member_api_docs
